/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package demo_RTO;

/**
 *
 * @author yashn
 */
public class RTO_Work_Space extends javax.swing.JPanel {

    /**
     * Creates new form manage_rto
     */
    public RTO_Work_Space() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manage_RTO = new javax.swing.JButton();
        Add_new_officer = new javax.swing.JButton();
        manage_officer = new javax.swing.JButton();

        Manage_RTO.setText("Manage RTO");
        Manage_RTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_RTOActionPerformed(evt);
            }
        });

        Add_new_officer.setText("Add New Officer");

        manage_officer.setText("Manage Officer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_new_officer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_officer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Manage_RTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Manage_RTO)
                .addGap(103, 103, 103)
                .addComponent(Add_new_officer)
                .addGap(108, 108, 108)
                .addComponent(manage_officer)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_RTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_RTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_RTOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_new_officer;
    private javax.swing.JButton Manage_RTO;
    private javax.swing.JButton manage_officer;
    // End of variables declaration//GEN-END:variables
}
