/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BuySellNetwork;

import Business.EcoSystem;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;
import UI.RTO.Add_RTO;

/**
 *
 * @author Saneel
 */
public class NetWork extends javax.swing.JPanel {

    /**
     * Creates new form OptnWork
     */
    private JPanel container;
    private EcoSystem system;

    public NetWork(JPanel container, EcoSystem system) {
        initComponents();
        this.container = container;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        ManageNetworkBtn = new javax.swing.JButton();
        RegisterEnterBtn = new javax.swing.JButton();
        ManageEnterprises = new javax.swing.JButton();
        btnRTO = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 234, 199));

        lblHeader.setBackground(new java.awt.Color(255, 255, 201));
        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("NetWork Work Area");

        ManageNetworkBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageNetworkBtn.setText("Manage Network");
        ManageNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageNetworkBtnActionPerformed(evt);
            }
        });

        RegisterEnterBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegisterEnterBtn.setText("Manage Enterprises");
        RegisterEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterEnterBtnActionPerformed(evt);
            }
        });

        ManageEnterprises.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageEnterprises.setText("Register Enterprises");
        ManageEnterprises.setPreferredSize(new java.awt.Dimension(100, 25));
        ManageEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterprisesActionPerformed(evt);
            }
        });

        btnRTO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRTO.setText("Add Transportation Office");
        btnRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRTOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 693, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRTO, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterEnterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageNetworkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(689, 689, 689))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ManageEnterprises, ManageNetworkBtn, RegisterEnterBtn, btnRTO});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(ManageNetworkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(ManageEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(RegisterEnterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnRTO)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ManageEnterprises, ManageNetworkBtn, RegisterEnterBtn, btnRTO});

    }// </editor-fold>//GEN-END:initComponents

    private void ManageNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageNetworkBtnActionPerformed
        // TODO add your handling code here:

        ManageNetwork mn = new ManageNetwork(container, system);   //create constructor in manage
        CardLayout layout = (CardLayout) container.getLayout();
        container.add(mn);
        layout.next(container);
    }//GEN-LAST:event_ManageNetworkBtnActionPerformed

    private void RegisterEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterEnterBtnActionPerformed
        // TODO add your handling code here:
        RegisterEnterprise re =new RegisterEnterprise(container,system); //create constructor
        CardLayout layout=(CardLayout)container.getLayout();
         container.add(re);
         layout.next(container);
    }//GEN-LAST:event_RegisterEnterBtnActionPerformed

    private void ManageEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterprisesActionPerformed
        // TODO add your handling code here:
        
        RegisterEnterprises r=new RegisterEnterprises(container,system); //create constructor
         CardLayout layout=(CardLayout)container.getLayout();
         container.add(r);
         layout.next(container);
    }//GEN-LAST:event_ManageEnterprisesActionPerformed

    private void btnRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRTOActionPerformed
        // TODO add your handling code here:
         Add_RTO r=new Add_RTO(container,system); //create constructor
         CardLayout layout=(CardLayout)container.getLayout();
         container.add(r);
         layout.next(container);
    }//GEN-LAST:event_btnRTOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEnterprises;
    private javax.swing.JButton ManageNetworkBtn;
    private javax.swing.JButton RegisterEnterBtn;
    private javax.swing.JButton btnRTO;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
