/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BuySellNetwork;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EPType;
import Business.Netwrk.Netwrk;
import Business.Role.AdminRole;
import Business.Role.LoanAdminRole;
import Business.Role.UserAdminRole;
import Business.User.User;
import Business.UserAccount.UserAcc;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import sun.security.util.Password;

/**
 *
 * @author saneel
 */
public class RegisterEnterprise extends javax.swing.JPanel {

    /**
     * Creates new form RegisterEnterprise
     */
    private JPanel container;
    private EcoSystem system;

    //constructor
    public RegisterEnterprise(JPanel container, EcoSystem system) {
        initComponents();

        this.container = container;
        this.system = system;
        populateTable();
        populatecbNetwork();
    }
    
    private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();

        model.setRowCount(0);
        for (Netwrk network : system.getNtwkLst()) {
            for (Enterprise enterprise : network.getEnpr().getEpLst()) {  //network enterprise directory
                for (UserAcc userAccount : enterprise.getUserAccDir().getUserAccs()) {    //organizations.useraccoutdirectory
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getNetwrkName();
                    row[2] = userAccount.getU_name();

                    model.addRow(row);
                }
            }
        }
    }

    private void populatecbNetwork() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        cbNetwork.removeAllItems(); //clear items if any
        cbEnterpriseType.removeAllItems();
        for (Netwrk network : system.getNtwkLst()) //ecosystem
        {
            cbNetwork.addItem(network);   //netwrk cannot be converted to string error

        }
        for (Enterprise.EPType type : Enterprise.EPType.values()) {
            cbEnterpriseType.addItem(type); //eptype cannot be converted to string

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblHeader = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRePass = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbNetwork = new javax.swing.JComboBox<>();
        cbEnterprises = new javax.swing.JComboBox<>();
        cbEnterpriseType = new javax.swing.JComboBox();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(240, 234, 199));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Enterpsises :");

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnterprise.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEnterprise);

        lblHeader.setBackground(new java.awt.Color(0, 0, 0));
        lblHeader.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("REGISTER ENTERPRISE");

        lblNetwork.setBackground(new java.awt.Color(0, 0, 0));
        lblNetwork.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNetwork.setText("Network :");

        lblEnterpriseType.setBackground(new java.awt.Color(0, 0, 0));
        lblEnterpriseType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEnterpriseType.setText("Enterprise Type:");

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setText("Name :");

        lblRePass.setBackground(new java.awt.Color(0, 0, 0));
        lblRePass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRePass.setText("Re-enter Password :");

        lblUserName.setBackground(new java.awt.Color(0, 0, 0));
        lblUserName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserName.setText("User Name :");

        lblPass.setBackground(new java.awt.Color(0, 0, 0));
        lblPass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPass.setText("Password :");

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNetworkActionPerformed(evt);
            }
        });

        cbEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterprisesActionPerformed(evt);
            }
        });

        cbEnterpriseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterpriseTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(lblPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRePass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(lblNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEnterpriseType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUserName)
                                .addComponent(cbEnterprises, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName)
                                .addComponent(txtPassword)
                                .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1676, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel7, lblEnterpriseType, lblName, lblNetwork, lblPass, lblRePass, lblUserName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnterpriseType))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName)))
                    .addComponent(lblNetwork))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRePass))
                .addGap(34, 34, 34)
                .addComponent(btnRegister)
                .addContainerGap(360, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(lblHeader)
                    .addContainerGap(928, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblEnterpriseType, lblName, lblNetwork, lblPass, lblRePass});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNetworkActionPerformed
        // TODO add your handling code here:
        Netwrk network = (Netwrk) cbNetwork.getSelectedItem();
    }//GEN-LAST:event_cbNetworkActionPerformed

    private void cbEnterpriseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterpriseTypeActionPerformed
        // TODO add your handling code here:
        Netwrk n = (Netwrk) cbNetwork.getSelectedItem();
        Enterprise.EPType ept = (Enterprise.EPType) cbEnterpriseType.getSelectedItem();
        populatecbEnterprises(n, ept);
    }//GEN-LAST:event_cbEnterpriseTypeActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
//        all text fields mandatory
        if (txtName.getText().isEmpty() || txtUserName.getText().isEmpty() || txtPassword.getText().isEmpty() || txtRePassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all boxes");
        } //if pass and re pass do not match then throw error msg
        else if (!txtPassword.getText().equals(txtRePassword.getText())) {
            JOptionPane.showMessageDialog(null, "Passwords doesnot match");
            return;
        } else {
            Enterprise e = (Enterprise) cbEnterprises.getSelectedItem();
            String username = txtUserName.getText();
            String password = String.valueOf(txtPassword.getText());   //getPassword
            String name = txtName.getText();
            if (e == null) {
                JOptionPane.showMessageDialog(null, "Please Select Enterprise");
                return;
            }
            User user = e.getUserDir().createUser(name);
            String er = cbEnterpriseType.getSelectedItem().toString();
            if ((cbEnterpriseType.getSelectedItem().toString()).equalsIgnoreCase("Service Center")) {
                for (UserAcc ua : e.getUserAccDir().getUserAccs()) {
                    if (ua.getU_name().equals(username)) {
                        JOptionPane.showMessageDialog(null, "This UserName Already Exists!");
                        return;
                    }
                }
                UserAcc account = e.getUserAccDir().createUserAcc(username, password, user, new AdminRole());
            } else if ((cbEnterpriseType.getSelectedItem().toString()).equalsIgnoreCase("User")) {
                for (UserAcc ua : e.getUserAccDir().getUserAccs()) {
                    if (ua.getU_name().equals(username)) {
                        JOptionPane.showMessageDialog(null, "This UserName Already Exists!");
                        return;
                    }
                }
                UserAcc account = e.getUserAccDir().createUserAcc(username, password, user, new UserAdminRole());
            } else if ((cbEnterpriseType.getSelectedItem().toString()).equalsIgnoreCase("Loan company")) {
                for (UserAcc ua : e.getUserAccDir().getUserAccs()) {
                    if (ua.getU_name().equals(username)) {
                        JOptionPane.showMessageDialog(null, "This UserName Already Exists!");
                        return;
                    }
                }
                UserAcc account = e.getUserAccDir().createUserAcc(username, password, user, new LoanAdminRole());
            }
            populateTable();

            JOptionPane.showMessageDialog(null, "Enterprise successfully registered!");
            txtName.setText("");
            txtUserName.setText("");
            txtPassword.setText(null);
            txtRePassword.setText(null);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cbEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterprisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEnterprisesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox cbEnterpriseType;
    private javax.swing.JComboBox<Enterprise> cbEnterprises;
    private javax.swing.JComboBox<Netwrk> cbNetwork;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRePass;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    

    private void populatecbEnterprises(Netwrk network, Enterprise.EPType t) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        cbEnterprises.removeAllItems();
        for (Enterprise e : network.getEnpr().getEpLst()) {
            if (e.getEPType().equals(t)) {
                cbEnterprises.addItem(e);  //enterprise cannot be converted to string
            }
        }
    }
}
    //network.enterprisedirectory..getenterpriselist
