/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.VehicleSeller;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organizations.SellerOrg;
import Business.UserAccount.UserAcc;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author saneel
 */

//manage seller is the initial page of the seller where the seller can view status, make changes to this creds, and ad this requirements
public class ManageSeller extends javax.swing.JPanel {

    /**
     * Creates new form ManageSeller
     */
//    public ManageSeller() {
//        initComponents();
    private JPanel container;
    private UserAcc account; //ua from b.ua
    private Enterprise enterprise;
    //private PatientDirectory pDir;
    private EcoSystem System;
    private SellerOrg organization; //sellerorg from b.o
    public ManageSeller(JPanel container, UserAcc account, SellerOrg organization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.container=container;
        this.account = account;
        this.organization = organization;
        this.System=business;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewSellerDetails = new javax.swing.JButton();
        btnSellVehicle = new javax.swing.JButton();
        btnSellerAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 234, 199));

        btnViewSellerDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewSellerDetails.setText("View Vehicle Details");
        btnViewSellerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSellerDetailsActionPerformed(evt);
            }
        });

        btnSellVehicle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSellVehicle.setText("I want to Sell My Vehicle");
        btnSellVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellVehicleActionPerformed(evt);
            }
        });

        btnSellerAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSellerAccount.setText("Account Holder Details");
        btnSellerAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellerAccountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Seller");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSellerAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(btnViewSellerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(btnSellVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(935, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnSellVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnViewSellerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnSellerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellVehicleActionPerformed
        // TODO add your handling code here:
//        takes me to new page where user can fill entries
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("SellVehicle", new SellVehicle(container, account, enterprise, System));
        layout.next(container);
        
    }//GEN-LAST:event_btnSellVehicleActionPerformed

    private void btnViewSellerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSellerDetailsActionPerformed
        // TODO add your handling code here:
        //takes us to view status page where we see status about page
        CardLayout layout = (CardLayout) container.getLayout();
      container.add("ViewStatus", new ViewStatus(container, account,enterprise, System));
      layout.next(container);
    }//GEN-LAST:event_btnViewSellerDetailsActionPerformed

    private void btnSellerAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellerAccountActionPerformed
        // TODO add your handling code here:
        
        //takes us to account holder page where we can update details about the user
         CardLayout layout = (CardLayout) container.getLayout();
        container.add("AccountHolder", new AccountHolder(container, account, enterprise));
        layout.next(container);
    }//GEN-LAST:event_btnSellerAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSellVehicle;
    private javax.swing.JButton btnSellerAccount;
    private javax.swing.JButton btnViewSellerDetails;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
