/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SC;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yashn/saneel
 */
public class SCWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form TCWorkAreaPanel
     */
    private JPanel container;
    private Enterprise ENPR;

    public SCWorkArea(JPanel container, Enterprise ENPR) {
        initComponents();

        this.container = container;
        this.ENPR = ENPR;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btnManageMech = new javax.swing.JButton();
        btnManageComp = new javax.swing.JButton();
        btnAddMechanic = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 234, 199));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Service Centre Work Area");

        btnManageMech.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageMech.setText("Manage Mechanic");
        btnManageMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMechActionPerformed(evt);
            }
        });

        btnManageComp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageComp.setText("Manage Company");
        btnManageComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCompActionPerformed(evt);
            }
        });

        btnAddMechanic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddMechanic.setText("Add a Mechanic");
        btnAddMechanic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMechanicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddMechanic, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageMech, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageComp, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHeader)
                .addGap(45, 45, 45)
                .addComponent(btnManageComp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnAddMechanic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnManageMech, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(573, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCompActionPerformed
        // TODO add your handling code here:
        ManageCompany mc = new ManageCompany(container, ENPR.getOrgDir());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add(mc);
        layout.next(container);
    }//GEN-LAST:event_btnManageCompActionPerformed

    private void btnAddMechanicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMechanicActionPerformed
        // TODO add your handling code here:
        
        //register mechanic
        AddMechanic addmech = new AddMechanic(container, ENPR.getOrgDir());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add(addmech);
        layout.next(container);
    }//GEN-LAST:event_btnAddMechanicActionPerformed

    private void btnManageMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMechActionPerformed
        // TODO add your handling code here:
        ManageMechanic mm = new ManageMechanic(container, ENPR);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add(mm);
        layout.next(container);
    }//GEN-LAST:event_btnManageMechActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMechanic;
    private javax.swing.JButton btnManageComp;
    private javax.swing.JButton btnManageMech;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
