/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.buyer;

import Business.EcoSystem;
//import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LoanComp;
import Business.Netwrk.Netwrk;
import Business.Organizations.LoanAgent;
import Business.Organizations.Organizations;
import Business.UserAccount.UserAcc;
import Business.WorkQueue.BuyerReqLoanComp;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saneel/yashn
 */
public class VehicleLoan extends javax.swing.JPanel {

    /**
     * Creates new form VehicleLoan
     */
    private JPanel container;
    private UserAcc uacc;
    private Enterprise ENPR;
    private Netwrk netwrk;
    private EcoSystem system;
    private Enterprise TC;
    private Netwrk lc;
    private String cost;

    public VehicleLoan(JPanel container, UserAcc uacc, Enterprise ENPR, Netwrk netwrk, EcoSystem system, Netwrk lc, Enterprise TC, String cost) {
        initComponents();

        this.container = container;
        this.uacc = uacc;
        this.ENPR = ENPR;
        this.netwrk = netwrk;
        this.system = system;
        this.lc = lc;
        this.TC = TC;
        this.cost = cost;

        populatetblLoanCompListTbl();
        populatecbLoanCompList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectAutoLoanComp = new javax.swing.JLabel();
        cbLoanCompList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoanCompList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnClaim = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 234, 199));

        lblSelectAutoLoanComp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelectAutoLoanComp.setText("Select Company from where you want to Take Vehicle Loan:");

        cbLoanCompList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoanCompListActionPerformed(evt);
            }
        });

        tblLoanCompList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Receiver", "Request Cost", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblLoanCompList);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnClaim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClaim.setText("Claim Request");
        btnClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(btnClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblSelectAutoLoanComp, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbLoanCompList, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(856, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoanCompList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectAutoLoanComp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnClaim)
                .addContainerGap(615, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimActionPerformed
        // TODO add your handling code here:
        Organizations org = null;
        for (Netwrk netwrk : system.getNtwkLst()) {
            for (Enterprise e : netwrk.getEnpr().getEpLst()) {
                for (Organizations oz : e.getOrgDir().getOrgLst()) {
                    if (netwrk.equals(lc)) {
                        if (e.equals(cbLoanCompList.getSelectedItem())) {
                            if (oz instanceof LoanAgent) {
                                org = oz;
                            }
                            break;
                        }
                    }
                }
            }
        }
        if (org != null) {
            BuyerReqLoanComp req = new BuyerReqLoanComp();
            req.setSender(uacc);
            req.setMsg(String.valueOf(cost));
            req.setStatus("Sent");
            org.getMoneyClaim().getWorkReqLst().add(req);
            uacc.getClaimMoney().getWorkReqLst().add(req);
            JOptionPane.showMessageDialog(null, "claim sent to Loan company!");
//            try{
//            Email emailConfig= new Email();
//            Properties smtpProperties = emailConfig.loadProperties();
//            String email = uacc.getU_name();
//            emailConfig.sendEmail(smtpProperties, email, "Request Initiated", " Request has been sent to Loan Company!");
//        }
//            catch(Exception ex){
//                
//            }
            populatetblLoanCompListTbl();

        }
        if (org == null) {
            JOptionPane.showMessageDialog(null, "No Loan Agent Organization has been created yet!");
        }
    }//GEN-LAST:event_btnClaimActionPerformed

    private void cbLoanCompListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoanCompListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoanCompListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClaim;
    private javax.swing.JComboBox<Enterprise> cbLoanCompList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectAutoLoanComp;
    private javax.swing.JTable tblLoanCompList;
    // End of variables declaration//GEN-END:variables

    public void populatetblLoanCompListTbl() {
        DefaultTableModel model = (DefaultTableModel) tblLoanCompList.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : uacc.getClaimMoney().getWorkReqLst()) {
            Object[] row = new Object[3];
            row[0] = wr.getReceiver();
            row[1] = wr.getMsg();
            row[2] = wr.getStatus();
            model.addRow(row);
        }
    }

    public void populatecbLoanCompList() {
        cbLoanCompList.removeAllItems();
        for (Enterprise er : lc.getEnpr().getEpLst()) {
            if (er instanceof LoanComp) {
                cbLoanCompList.addItem(er);
            }
        }
    }
}
