/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RTO;

import Business.Buyer.Buyer;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organizations.BuyerOrg;
import Business.Organizations.MechanicOrg;
import Business.Organizations.Organizations;
import Business.Organizations.RtoOrg;
import Business.UserAccount.UserAcc;
import Business.WorkQueue.RTOWorkReq;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yashn
 */
public class Check_Report extends javax.swing.JPanel {

    /**
     * Creates new form Check_Report
     */
    DB4OUtil db4oUtil;
    
    private RtoOrg rtoOrg;
    private Organizations org;
    private UserAcc account;
    private JPanel container;

    private Enterprise enterprise;
    private EcoSystem System;
    /*public Check_Report(JPanel container, UserAcc account, Enterprise enterprise, EcoSystem Business) {
//        db4oUtil = DB4OUtil.getInstance();
//        this.system = db4oUtil.retrieveSystem();

        initComponents();
        this.container = container;
        this.account = account;
        this.enterprise = enterprise;
        this.System = System;
        //submitbtn.setEnabled(false);
       
        populateBuyerList(); //location
    }*/

    public Check_Report(JPanel container, UserAcc account, Organizations organization, Enterprise enterprise, EcoSystem business) {
         initComponents();
        this.container = container;
        this.account = account;
        this.enterprise = enterprise;
        this.System = System;
        //submitbtn.setEnabled(false);
       
        populateBuyerList(); //location
    }

    private void populateBuyerList() {
        //System.out.println("Network List : " + rtoOrg.getName());
//        ArrayList<WorkRequest> buyersList = BuyerOrg.getWorkQueue().getWorkReqLst();
//        for (int i = 0; i < buyersList.size(); i++) {
//            System.out.println("Example List : " + buyersList.get(i).getRole());
//           
//        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkReqLst()) {
            if (request instanceof RTOWorkReq) {
                Object[] row = new Object[3];
                row[0] = request.getSender().getU_name();
                //row[0] = ((RTOWorkReq) request);
                row[1] = ((RTOWorkReq) request).getSeller();
//    row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row[2] = ((RTOWorkReq) request).getMechanic();

                model.addRow(row);
            }
        }
    }

    private void populateDealerList() {

    }

    private void populateSellerList() {

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Report of Vehicle Trade between buyer and seller");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", ""},
                {"", "", ""},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Buyer", "Seller", "Dealer"
            }
        ));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(102, 102, 102)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
