/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Users;

/**
 *
 * @author yashn
 */
public class Use_Work_Area extends javax.swing.JPanel {

    /**
     * Creates new form Use_Work_Area
     */
    public Use_Work_Area() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manage_User_Btn = new javax.swing.JButton();
        ManageCompnayBtn = new javax.swing.JButton();
        Add_User_Btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        Manage_User_Btn.setText("Manage User");
        Manage_User_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_User_BtnActionPerformed(evt);
            }
        });

        ManageCompnayBtn.setText("Manage Compnay");
        ManageCompnayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCompnayBtnActionPerformed(evt);
            }
        });

        Add_User_Btn.setText("Add User");
        Add_User_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_User_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageCompnayBtn)
                    .addComponent(Manage_User_Btn))
                .addGap(323, 323, 323))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(359, 359, 359)
                    .addComponent(Add_User_Btn)
                    .addContainerGap(325, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Add_User_Btn, ManageCompnayBtn, Manage_User_Btn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ManageCompnayBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(Manage_User_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(Add_User_Btn)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Add_User_Btn, ManageCompnayBtn, Manage_User_Btn});

    }// </editor-fold>//GEN-END:initComponents

    private void Manage_User_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_User_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_User_BtnActionPerformed

    private void ManageCompnayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCompnayBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageCompnayBtnActionPerformed

    private void Add_User_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_User_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_User_BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_User_Btn;
    private javax.swing.JButton ManageCompnayBtn;
    private javax.swing.JButton Manage_User_Btn;
    // End of variables declaration//GEN-END:variables
}
