/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InsuranceCompany;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import LoanCompany.ManageIncComp;
import LoanCompany.AgentRegistration;
import LoanCompany.AgentManage;

/**
 *
 * @author saneel/yash/harsh
 */
public class CompanyManagement extends javax.swing.JPanel {

    /**
     * Creates new form ManageIncComp
     */
    private JPanel container;
    private Enterprise enpr;

    public CompanyManagement(JPanel container, Enterprise enpr) {
        initComponents();
        this.container = container;
        this.enpr = enpr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngeComp = new javax.swing.JButton();
        btnAddAgent = new javax.swing.JButton();
        btnMngeAgent = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 234, 199));

        btnMngeComp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMngeComp.setText("Manage Loan Company");
        btnMngeComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngeCompActionPerformed(evt);
            }
        });

        btnAddAgent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddAgent.setText("Add New Agents");
        btnAddAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAgentActionPerformed(evt);
            }
        });

        btnMngeAgent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMngeAgent.setText("Manage Agent");
        btnMngeAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngeAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngeAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngeComp, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(798, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddAgent, btnMngeAgent, btnMngeComp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnMngeComp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnAddAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnMngeAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddAgent, btnMngeAgent, btnMngeComp});

    }// </editor-fold>//GEN-END:initComponents

    private void btnMngeCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngeCompActionPerformed
        // TODO add your handling code here:
        ManageIncComp mic = new ManageIncComp(container, enpr.getOrgDir());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add(mic);
        layout.next(container);
    }//GEN-LAST:event_btnMngeCompActionPerformed

    private void btnAddAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAgentActionPerformed
        // TODO add your handling code here:
        AgentRegistration rc = new AgentRegistration(container, enpr.getOrgDir());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add(rc);
        layout.next(container);
    }//GEN-LAST:event_btnAddAgentActionPerformed

    private void btnMngeAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngeAgentActionPerformed
        // TODO add your handling code here:
        AgentManage ma = new AgentManage(container, enpr);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add(ma);
        layout.next(container);
    }//GEN-LAST:event_btnMngeAgentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAgent;
    private javax.swing.JButton btnMngeAgent;
    private javax.swing.JButton btnMngeComp;
    // End of variables declaration//GEN-END:variables
}
